// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbjlwzcemggatrnxlxgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiamx3emNlbWdnYXRybnhseGdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDA2OTYsImV4cCI6MjA1OTg3NjY5Nn0.6Cvs1iQ2uIUN62yRIxDJqkKT1oMFHmX9LU2M2-1BE-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);