
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acuhjfxobafthcjbjzro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjdWhqZnhvYmFmdGhjamJqenJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODc4NzIsImV4cCI6MjA1OTk2Mzg3Mn0.ES5S1bhanI2L3Mxj7S7Yl_98j7eIuuvWfJu5icfu-6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
